name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.9.0
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      # todo: add lint here
      - run: pnpm run build
